'use strict';
/**
 * lib/salesPosting/post.js — claim queue rows, post ONE journal, record the batch.
 *
 * The DB-touching half of «ترحيل المبيعات». The arithmetic lives in
 * ./aggregate.js and is pure; this file adds only the things that need a
 * transaction: claiming, posting, recording, and reversing.
 *
 * ─── WHY THE CLAIM IS AN EXPLICIT ID LIST ───────────────────────────────────
 *
 * `UPDATE … WHERE id IN (1,2,3) AND status = 'pending'` and then trusting
 * `affectedRows` as the set actually won. A range predicate
 * (`WHERE business_day = ?`) would be shorter and would take gap locks over
 * the range a concurrent CHECKOUT is inserting into — so a contended posting
 * run would block the till. Any lock contention path that reaches the register
 * is unacceptable, so the claim only ever names rows that already exist.
 *
 * ─── WHY NOTHING HERE IS IDEMPOTENT BY ACCIDENT ─────────────────────────────
 *
 * `postJournal` never looks for an existing journal by reference, and
 * `ix_glj_ref` is deliberately non-unique. A retry after a crash between "the
 * journal committed" and "the queue rows were marked posted" would therefore
 * create a SECOND complete journal and apply `gl_accounts.balance` twice, with
 * `{success:true}` both times.
 *
 * Three layers stop that:
 *   1. `uq_spb_idem` — the same idempotency key cannot insert twice.
 *   2. the conditional claim — a row already `posting`/`posted` is not won.
 *   3. claim + post + record all happen in ONE transaction, so there is no
 *      window in which the journal exists but the rows are still pending.
 *
 * ─── created_by vs posted_by ────────────────────────────────────────────────
 *
 * `created_by = 'system:sales-posting'`, `posted_by` = the human. The batch is
 * GENERATED by the system from documents that are already filed — the same
 * stance `_generateClosingEntries` takes for year-end. It also matters
 * mechanically: `checkSelfApproval` compares `created_by` to the acting user,
 * so recording the human as creator would forbid them from posting their own
 * batch under maker/checker.
 */

const glPosting = require('../glPosting');
const glTransitions = require('../glTransitions');
const aggregate = require('./aggregate');

/** Journals produced by this subsystem. Nothing else may use it. */
const REFERENCE_TYPE = 'SalesBatch';

/**
 * Resolve the account codes a batch posts to.
 *
 * Mirrors routes/sales.js#_resolveSaleGlCodes so a chart import that
 * renumbers revenue/VAT/COGS/inventory moves the batch and the sale together.
 * Falling back to the canonical core codes is safe because
 * `ensureCoreAccounts` seeds them on first post.
 */
async function resolveAccounts(conn) {
  const A = glPosting.CORE_ACCOUNTS;
  const codes = {
    revenue: A.SALES_REVENUE.code, outputVat: A.OUTPUT_VAT.code,
    cogs: A.COGS.code, inventory: A.INVENTORY.code,
    cashFallback: A.CASH.code, platformCommission: A.PLATFORM_COMMISSION.code,
    platformPayable: A.PLATFORM_PAYABLE.code,
  };
  const keyMap = {
    revenue: 'GL_SALES_REVENUE_CODE',
    outputVat: 'GL_OUTPUT_VAT_CODE',
    cogs: 'GL_COGS_CODE',
    inventory: 'GL_INVENTORY_CODE',
    cashFallback: 'GL_CASH_CODE',
    platformCommission: 'GL_PLATFORM_COMMISSION_CODE',
    platformPayable: 'GL_PLATFORM_PAYABLE_CODE',
  };
  try {
    const keys = Object.values(keyMap);
    const [rows] = await conn.query(
      `SELECT setting_key, setting_value FROM settings WHERE setting_key IN (${keys.map(() => '?').join(',')})`,
      keys);
    const s = {};
    rows.forEach((r) => { s[r.setting_key] = r.setting_value; });
    for (const [field, key] of Object.entries(keyMap)) {
      const v = s[key];
      if (v != null && String(v).trim() !== '') codes[field] = String(v).trim();
    }
  } catch (_) { /* settings table missing on a legacy deploy — keep core codes */ }
  return codes;
}

const WHERE_PENDING = "status IN ('pending', 'failed')";

/** Build the shared filter clause for the pending queue. */
function pendingFilter(f = {}) {
  const where = [WHERE_PENDING];
  const args = [];
  if (f.from) { where.push('calendar_date >= ?'); args.push(f.from); }
  if (f.to) { where.push('calendar_date <= ?'); args.push(f.to); }
  if (f.brandId) { where.push('brand_id = ?'); args.push(f.brandId); }
  if (f.branchId) { where.push('branch_id = ?'); args.push(f.branchId); }
  return { sql: where.join(' AND '), args };
}

/** Read the pending queue. */
async function listPending(conn, filters = {}) {
  const { sql, args } = pendingFilter(filters);
  const [rows] = await conn.query(
    `SELECT id, source_type, source_id, business_day, calendar_date, brand_id, branch_id,
            net_amount, tax_amount, gross_amount, cogs_amount, payload_json,
            invoice_number, status, attempts, last_error
       FROM sales_posting_queue
      WHERE ${sql}
      ORDER BY calendar_date, id`, args);
  return rows;
}

/** Atomically allocate the next durable generation for one bucket. */
async function nextPostingCycle(conn, granularity, bucketKey) {
  await conn.query(
    `INSERT INTO sales_posting_bucket_sequences (granularity, bucket_key, last_cycle)
     VALUES (?, ?, 1)
     ON DUPLICATE KEY UPDATE last_cycle = last_cycle + 1`,
    [granularity, bucketKey]);
  const [[row]] = await conn.query(
    `SELECT last_cycle
       FROM sales_posting_bucket_sequences
      WHERE granularity = ? AND bucket_key = ?
      FOR UPDATE`,
    [granularity, bucketKey]);
  const cycle = Number(row && row.last_cycle);
  if (!Number.isInteger(cycle) || cycle < 1) {
    const e = new Error('sales posting cycle allocation failed');
    e.code = 'cycle_allocation_failed'; e.status = 500; throw e;
  }
  return cycle;
}

/**
 * PREVIEW. The same plan that posting will use — `planBatches` is pure, so
 * this is not a second implementation that agrees today and drifts later.
 * Mandatory before posting: this path is what turns a broken chart of accounts
 * from a silent failure into something a human can see first.
 */
async function preview(conn, { granularity = 'daily', filters = {} } = {}) {
  if (!aggregate.GRANULARITIES.includes(granularity)) {
    const e = new Error('granularity must be daily or monthly'); e.status = 400; throw e;
  }
  const accounts = await resolveAccounts(conn);
  const rows = await listPending(conn, filters);
  return { accounts, batches: aggregate.planBatches(rows, granularity, accounts) };
}

/**
 * POST one bucket. All-or-nothing inside a single transaction.
 *
 * @param {object} pool  the app pool (this opens its own transaction)
 * @param {{granularity, bucketKey, actor, idempotencyKey, reason}} opts
 */
async function postBatch(pool, opts) {
  const { granularity = 'daily', bucketKey, actor, filters = {} } = opts;
  if (!aggregate.GRANULARITIES.includes(granularity)) {
    const e = new Error('granularity must be daily or monthly'); e.status = 400; throw e;
  }
  if (!bucketKey) { const e = new Error('bucketKey is required'); e.status = 400; throw e; }
  return pool.withTransaction(async (conn) => {
    const accounts = await resolveAccounts(conn);
    const rows = await listPending(conn, filters);
    const plan = aggregate.planBatches(rows, granularity, accounts);
    const bucket = plan.find((b) => b.key === bucketKey);
    if (!bucket) { const e = new Error('bucket not found or already posted'); e.code = 'bucket_not_found'; e.status = 404; throw e; }
    if (!bucket.postable) {
      const e = new Error('batch is not postable: ' + bucket.warnings.join(' · '));
      e.code = 'not_postable'; e.status = 422; e.warnings = bucket.warnings; throw e;
    }
    if (!bucket.legs.length) { const e = new Error('nothing to post'); e.code = 'empty_batch'; e.status = 422; throw e; }

    // Claim first; only the transaction that wins the whole explicit set may
    // allocate the bucket's next durable generation below.
    const ids = bucket.queueIds;

    // ── 1. CLAIM ──────────────────────────────────────────────────────────
    // Explicit ids, conditional on still being pending. `affectedRows` is the
    // set this call actually won; anything else was taken by a concurrent run
    // and must not be posted here.
    const [claim] = await conn.query(
      `UPDATE sales_posting_queue
          SET status = 'posting'
        WHERE id IN (${ids.map(() => '?').join(',')})
          AND status IN ('pending', 'failed')`, ids);
    if (claim.affectedRows !== ids.length) {
      const e = new Error('another posting run claimed ' + (ids.length - claim.affectedRows) +
        ' of these ' + ids.length + ' row(s) — re-run the preview');
      e.code = 'claim_conflict'; e.status = 409; throw e;
    }

    // Allocate only after this transaction has won every queue row. The
    // bucket counter is row-locked and incremented in this transaction, so a
    // later sale in an already-posted day/month receives a fresh generation.
    const cycle = await nextPostingCycle(conn, granularity, bucketKey);
    const suffix = ':cycle:' + cycle;
    const baseKey = String(opts.idempotencyKey || (granularity + ':' + bucketKey));
    const idempotencyKey = baseKey.slice(0, Math.max(0, 120 - suffix.length)) + suffix;

    // ── 2. POST ───────────────────────────────────────────────────────────
    // On the transaction connection, so the journal and the queue state are
    // one unit. There is no window where the journal exists and the rows are
    // still pending — which is the window a retry would double-post through.
    await glPosting.ensureCoreAccounts(conn);
    const posted = await glPosting.postJournal(conn, {
      journalDate: bucket.journalDate,
      description: 'ترحيل مبيعات ' + bucket.label +
        ' — ' + bucket.salesCount + ' بيعة' +
        (bucket.returnCount ? ' و' + bucket.returnCount + ' مرتجع' : ''),
      referenceType: REFERENCE_TYPE,
      referenceId: bucketKey,
      entries: bucket.legs.map((l) => ({
        accountCode: l.accountCode,
        debit: l.debit, credit: l.credit,
        description: 'ترحيل مبيعات ' + bucket.label,
        brandId: bucket.brandId || null,
        branchId: bucket.branchId || null,
        warehouseId: l.warehouseId || null,
      })),
      postedBy: actor || '',
      status: 'posted',
    });
    if (!posted || !posted.success) {
      const e = new Error('GL post failed: ' + ((posted && posted.error) || 'unknown'));
      e.code = 'gl_post_failed'; e.status = 500; throw e;
    }

    // ── 3. RECORD ─────────────────────────────────────────────────────────
    const batchId = 'SPB-' + (posted.journalNumber || posted.journalId);
    await conn.query(
      `INSERT INTO sales_posting_batches
         (id, granularity, bucket_key, brand_id, branch_id, journal_date, journal_id,
          status, item_count, net_amount, tax_amount, gross_amount, cogs_amount,
          legs_json, idempotency_key, created_by, posted_by, posted_at)
       VALUES (?,?,?,?,?,?,?, 'posted', ?,?,?,?,?, ?,?, 'system:sales-posting', ?, NOW())`,
      [batchId, granularity, bucketKey, bucket.brandId, bucket.branchId,
       bucket.journalDate, posted.journalId,
       bucket.itemCount, bucket.net, bucket.tax, bucket.gross, bucket.cogs,
       JSON.stringify(bucket.legs), idempotencyKey, actor || '']);

    // Append-only membership, so "which batch was this invoice in" stays
    // answerable after a reversal puts the rows back to pending.
    for (const s of bucket.sources) {
      await conn.query(
        `INSERT INTO sales_posting_batch_items
           (batch_id, queue_id, source_type, source_id, net_amount, tax_amount, gross_amount)
         VALUES (?,?,?,?,?,?,?)`,
        [batchId, s.id, s.type, s.sourceId, s.net, s.tax, s.gross]);
    }

    await conn.query(
      `UPDATE sales_posting_queue
          SET status = 'posted', batch_id = ?, posted_at = NOW(), last_error = NULL
        WHERE id IN (${ids.map(() => '?').join(',')})`, [batchId, ...ids]);

    // Preserve invoice-to-ledger traceability without creating one journal
    // per invoice: many POS documents may point at this aggregated journal.
    const saleIds = bucket.sources.filter((s) => s.type === 'sale').map((s) => s.sourceId);
    if (saleIds.length) {
      await conn.query(
        `UPDATE ar_documents
            SET gl_journal_id = ?
          WHERE source_type = 'pos'
            AND source_id IN (${saleIds.map(() => '?').join(',')})`,
        [posted.journalId, ...saleIds]);
    }

    return {
      batchId,
      journalId: posted.journalId,
      journalNumber: posted.journalNumber,
      journalDate: bucket.journalDate,
      itemCount: bucket.itemCount,
      net: bucket.net, tax: bucket.tax, gross: bucket.gross,
      legs: bucket.legs,
    };
  });
}

/**
 * REVERSE a posted batch.
 *
 * Reuses glTransitions.reverse as-is — it already refuses a non-posted or
 * already-reversed journal, copies every dimension, and links both directions
 * atomically. Re-implementing any of that here would be a second set of rules
 * to keep in step.
 *
 * The queue rows go back to `pending`, so the accountant fixes whatever was
 * wrong and posts them again. Their batch_items rows stay — the history of
 * which batch they were in on the day is append-only.
 */
async function reverseBatch(pool, { batchId, actor, reason }) {
  return pool.withTransaction(async (conn) => {
  const [[batch]] = await conn.query(
    'SELECT * FROM sales_posting_batches WHERE id = ? LIMIT 1 FOR UPDATE', [batchId]);
  if (!batch) { const e = new Error('batch not found'); e.code = 'not_found'; e.status = 404; throw e; }
  if (batch.status !== 'posted') {
    const e = new Error('only a posted batch can be reversed'); e.code = 'not_posted'; e.status = 400; throw e;
  }
  if (!batch.journal_id) {
    const e = new Error('batch has no journal to reverse'); e.code = 'no_journal'; e.status = 400; throw e;
  }

  // The reversal is dated in the batch's OWN period, not today. Reversing a
  // month-end batch in the following month would move the correction into a
  // period the original never touched — and would be rejected outright once
  // that month is closed.
  const rev = await glTransitions.reverse(batch.journal_id, { username: actor || 'system' }, {
    reason: reason || ('عكس دفعة ترحيل مبيعات ' + batchId),
    journalDate: batch.journal_date,
    conn,
  });

  if (!rev || !rev.ok || !rev.newJournalId) {
    const e = new Error((rev && rev.message) || 'sales batch GL reversal failed');
    e.code = (rev && rev.code) || 'batch_reversal_failed';
    e.status = (rev && rev.status) || 500;
    throw e;
  }

  const [batchUpdate] = await conn.query(
    `UPDATE sales_posting_batches
        SET status = 'reversed', reversal_journal_id = ?, reversed_at = NOW(),
            reversed_by = ?, reverse_reason = ?
      WHERE id = ?`,
    [rev.newJournalId, actor || '', String(reason || '').slice(0, 300), batchId]);
  if (!batchUpdate || batchUpdate.affectedRows !== 1) {
    const e = new Error('sales batch state changed during reversal');
    e.code = 'batch_reversal_conflict'; e.status = 409; throw e;
  }

  const [back] = await conn.query(
    `UPDATE sales_posting_queue
        SET status = 'pending', batch_id = NULL, posted_at = NULL
      WHERE batch_id = ?`, [batchId]);

  // Do not leave an invoice pointing at a journal that has been reversed.
  // Append-only batch membership remains the permanent audit trail.
  await conn.query(
    `UPDATE ar_documents d
       JOIN sales_posting_batch_items i
         ON i.source_type = 'sale' AND i.source_id = d.source_id
        SET d.gl_journal_id = NULL
      WHERE i.batch_id = ? AND d.source_type = 'pos' AND d.gl_journal_id = ?`,
    [batchId, batch.journal_id]);

  return { batchId, reversal: rev, requeued: back.affectedRows };
  });
}

module.exports = {
  listPending,
  preview,
  postBatch,
  reverseBatch,
  resolveAccounts,
  pendingFilter,
  nextPostingCycle,
  REFERENCE_TYPE,
};
